name: 'Jira Release Link'
description: 'Assigns Jira issues to a release version by version name and ticket list'
inputs:
  jira-email:
    required: true
    description: 'Jira user email'
  jira-token:
    required: true
    description: 'Jira API token'
  jira-domain:
    required: true
    description: 'Jira domain (e.g. company.atlassian.net)'
  jira-project:
    required: true
    description: 'Jira project key'
  jira-ticket-key-prefix:
    required: false
    description: 'Jira ticket key prefix (e.g. TICKET)'
  release-name:
    required: true
    description: 'Release name (e.g. Release 1.0.0)'
  release-name-regex:
    required: false
    description: 'Regex to check if ticket has release already assigned (e.g. Release ([0-9]+)). If not provided - check is skipped.'

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm install
      shell: bash
    - name: Assign Jira tickets to release
      run: node assign-tickets.js
      shell: bash
